### ISSUE TITLE
Failed to initialize NVML: Unknown Error - Even after reading the pinned issue

### ISSUE THREAD

**Issue by mfuntowicz** [NVIDIA/nvidia-container-toolkit#381]
Hi, 

I'm trying to understand what I might be missing with my devbox which suddenly loose access to GPUs with Docker with the above message **"Failed to initialize NVML: Unknown Error"**.

I spot the pinned issue https://github.com/NVIDIA/nvidia-container-toolkit/issues/48 and followed the steps to workaround the issue but it's still there 😭.

Something I'm noticing regarding the "**How to check if you are affected**", I have slightly different outputs and no actual error after `sudo systemctl daemon-reload`:

expected: 

```
➜  open-gpu-kernel-modules git:(550.54.14) docker logs 3ff77b4177ffd8445efb09133404143dd8356d5411c2473eeb56cd8872b03a5e
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
Failed to initialize NVML: Unknown Error
Failed to initialize NVML: Unknown Error
```

current:
```
➜  open-gpu-kernel-modules git:(550.54.14) docker logs 3ff77b4177ffd8445efb09133404143dd8356d5411c2473eeb56cd8872b03a5e
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
GPU 0: NVIDIA GeForce RTX 4090 (UUID: GPU-64e84141-e88f-1449-50cc-2cb96be330ab)
```

Last but not least, the suggested command line invocation to create `/dev/char` doesn't work on my side:

```
➜  open-gpu-kernel-modules git:(550.54.14) sudo nvidia-ctk system create-dev-char-symlinks --create-all
ERRO[0000] failed to create symlink creator: failed to create all possible device lister: missing required device major nvidia-frontend
```

Thanks in advance 🙏

I'm attaching my `/etc/docker/daemon.json` along with `docker info` in case it can help:

```
➜  open-gpu-kernel-modules git:(550.54.14) nvidia-smi
Wed Feb 28 10:27:37 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:65:00.0 Off |                  Off |
| 30%   33C    P0             66W /  450W |       0MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

```json
{
    "default-runtime": "nvidia",
    "exec-opts": [
        "native.cgroupdriver=cgroupfs"
    ],
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```

```
➜  open-gpu-kernel-modules git:(550.54.14) docker info
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.6
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 30
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.7.6-200.fc39.x86_64
 Operating System: Fedora Linux 39 (Server Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 251.4GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mfuntowicz
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by elezar** [comment]
> ERRO[0000] failed to create symlink creator: failed to create all possible device lister: missing required device major nvidia-frontend

As part of the 550 driver release, the `nvidia-frontend` driver file name was renamed `nvidia`. This means that the tooling is failing due to `nvidia-frontend` not being present. We should publish the `v1.14.6` update to our NVIDIA Container Toolkit later today to address this.

**Comment by mfuntowicz** [comment]
Awesome, thanks! Will give it a try when it's out

**Comment by elezar** [comment]
> Awesome, thanks! Will give it a try when it's out

https://github.com/NVIDIA/nvidia-container-toolkit/releases/tag/v1.14.6 has been released. Please let us know if there are still problems with it.

**Comment by mfuntowicz** [comment]
@elezar I just updated to v1.14.6, redid the steps in #48 to workaround (the /dev/char creation now works - thanks 👍🏻) but still facing the issue :

```bash
➜  open-gpu-kernel-modules git:(550.54.14) docker run -it --rm --gpus all huggingface/optimum-nvidia:0.1.0b3 bash

=============
== PyTorch ==
=============

NVIDIA Release 23.12 (build 76438008)
PyTorch Version 2.2.0a0+81ea7a4

Container image Copyright (c) 2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

Copyright (c) 2014-2023 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

ERROR: The NVIDIA Driver is present, but CUDA failed to initialize.  GPU functionality will not be available.
   [[ No CUDA-capable device is detected (error 100) ]]

Failed to detect NVIDIA driver version.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...

root@9a8a00f2a911:/opt/optimum-nvidia/examples# nvidia-smi
Failed to initialize NVML: Unknown Error
```


```bash
➜  open-gpu-kernel-modules git:(550.54.14) sudo nvidia-ctk system create-dev-char-symlinks --create-all
INFO[0000] Creating link /dev/char/195:254 => /dev/nvidia-modeset
INFO[0000] Creating link /dev/char/195:255 => /dev/nvidiactl
WARN[0000] Could not create symlink: symlink /dev/nvidiactl /dev/char/195:255: file exists
INFO[0000] Creating link /dev/char/507:0 => /dev/nvidia-uvm
WARN[0000] Could not create symlink: symlink /dev/nvidia-uvm /dev/char/507:0: file exists
INFO[0000] Creating link /dev/char/507:1 => /dev/nvidia-uvm-tools
WARN[0000] Could not create symlink: symlink /dev/nvidia-uvm-tools /dev/char/507:1: file exists
INFO[0000] Creating link /dev/char/235:1 => /dev/nvidia-caps/nvidia-cap1
WARN[0000] Could not create symlink: symlink /dev/nvidia-caps/nvidia-cap1 /dev/char/235:1: file exists
INFO[0000] Creating link /dev/char/235:2 => /dev/nvidia-caps/nvidia-cap2
WARN[0000] Could not create symlink: symlink /dev/nvidia-caps/nvidia-cap2 /dev/char/235:2: file exists
INFO[0000] Creating link /dev/char/195:0 => /dev/nvidia0
WARN[0000] Could not create symlink: symlink /dev/nvidia0 /dev/char/195:0: file exists
INFO[0000] Creating link /dev/char/235:3 => /dev/nvidia-caps/nvidia-cap3
INFO[0000] Creating link /dev/char/235:4 => /dev/nvidia-caps/nvidia-cap4
INFO[0000] Creating link /dev/char/235:5 => /dev/nvidia-caps/nvidia-cap5
INFO[0000] Creating link /dev/char/235:6 => /dev/nvidia-caps/nvidia-cap6
INFO[0000] Creating link /dev/char/235:7 => /dev/nvidia-caps/nvidia-cap7
INFO[0000] Creating link /dev/char/235:8 => /dev/nvidia-caps/nvidia-cap8
INFO[0000] Creating link /dev/char/235:9 => /dev/nvidia-caps/nvidia-cap9
INFO[0000] Creating link /dev/char/235:10 => /dev/nvidia-caps/nvidia-cap10
INFO[0000] Creating link /dev/char/235:11 => /dev/nvidia-caps/nvidia-cap11
INFO[0000] Creating link /dev/char/235:12 => /dev/nvidia-caps/nvidia-cap12
INFO[0000] Creating link /dev/char/235:13 => /dev/nvidia-caps/nvidia-cap13
INFO[0000] Creating link /dev/char/235:14 => /dev/nvidia-caps/nvidia-cap14
INFO[0000] Creating link /dev/char/235:15 => /dev/nvidia-caps/nvidia-cap15
INFO[0000] Creating link /dev/char/235:16 => /dev/nvidia-caps/nvidia-cap16
INFO[0000] Creating link /dev/char/235:17 => /dev/nvidia-caps/nvidia-cap17
INFO[0000] Creating link /dev/char/235:18 => /dev/nvidia-caps/nvidia-cap18
INFO[0000] Creating link /dev/char/235:19 => /dev/nvidia-caps/nvidia-cap19
INFO[0000] Creating link /dev/char/235:20 => /dev/nvidia-caps/nvidia-cap20
INFO[0000] Creating link /dev/char/235:21 => /dev/nvidia-caps/nvidia-cap21
INFO[0000] Creating link /dev/char/235:22 => /dev/nvidia-caps/nvidia-cap22
INFO[0000] Creating link /dev/char/235:23 => /dev/nvidia-caps/nvidia-cap23
INFO[0000] Creating link /dev/char/235:24 => /dev/nvidia-caps/nvidia-cap24
INFO[0000] Creating link /dev/char/235:25 => /dev/nvidia-caps/nvidia-cap25
INFO[0000] Creating link /dev/char/235:26 => /dev/nvidia-caps/nvidia-cap26
INFO[0000] Creating link /dev/char/235:27 => /dev/nvidia-caps/nvidia-cap27
INFO[0000] Creating link /dev/char/235:28 => /dev/nvidia-caps/nvidia-cap28
INFO[0000] Creating link /dev/char/235:29 => /dev/nvidia-caps/nvidia-cap29
INFO[0000] Creating link /dev/char/235:30 => /dev/nvidia-caps/nvidia-cap30
INFO[0000] Creating link /dev/char/235:31 => /dev/nvidia-caps/nvidia-cap31
INFO[0000] Creating link /dev/char/235:32 => /dev/nvidia-caps/nvidia-cap32
INFO[0000] Creating link /dev/char/235:33 => /dev/nvidia-caps/nvidia-cap33
INFO[0000] Creating link /dev/char/235:34 => /dev/nvidia-caps/nvidia-cap34
INFO[0000] Creating link /dev/char/235:35 => /dev/nvidia-caps/nvidia-cap35
INFO[0000] Creating link /dev/char/235:36 => /dev/nvidia-caps/nvidia-cap36
INFO[0000] Creating link /dev/char/235:37 => /dev/nvidia-caps/nvidia-cap37
INFO[0000] Creating link /dev/char/235:38 => /dev/nvidia-caps/nvidia-cap38
INFO[0000] Creating link /dev/char/235:39 => /dev/nvidia-caps/nvidia-cap39
INFO[0000] Creating link /dev/char/235:40 => /dev/nvidia-caps/nvidia-cap40
INFO[0000] Creating link /dev/char/235:41 => /dev/nvidia-caps/nvidia-cap41
INFO[0000] Creating link /dev/char/235:42 => /dev/nvidia-caps/nvidia-cap42
INFO[0000] Creating link /dev/char/235:43 => /dev/nvidia-caps/nvidia-cap43
INFO[0000] Creating link /dev/char/235:44 => /dev/nvidia-caps/nvidia-cap44
INFO[0000] Creating link /dev/char/235:45 => /dev/nvidia-caps/nvidia-cap45
INFO[0000] Creating link /dev/char/235:46 => /dev/nvidia-caps/nvidia-cap46
INFO[0000] Creating link /dev/char/235:47 => /dev/nvidia-caps/nvidia-cap47
INFO[0000] Creating link /dev/char/235:48 => /dev/nvidia-caps/nvidia-cap48
INFO[0000] Creating link /dev/char/235:49 => /dev/nvidia-caps/nvidia-cap49
INFO[0000] Creating link /dev/char/235:50 => /dev/nvidia-caps/nvidia-cap50
INFO[0000] Creating link /dev/char/235:51 => /dev/nvidia-caps/nvidia-cap51
INFO[0000] Creating link /dev/char/235:52 => /dev/nvidia-caps/nvidia-cap52
INFO[0000] Creating link /dev/char/235:53 => /dev/nvidia-caps/nvidia-cap53
INFO[0000] Creating link /dev/char/235:54 => /dev/nvidia-caps/nvidia-cap54
INFO[0000] Creating link /dev/char/235:55 => /dev/nvidia-caps/nvidia-cap55
INFO[0000] Creating link /dev/char/235:56 => /dev/nvidia-caps/nvidia-cap56
INFO[0000] Creating link /dev/char/235:57 => /dev/nvidia-caps/nvidia-cap57
INFO[0000] Creating link /dev/char/235:58 => /dev/nvidia-caps/nvidia-cap58
INFO[0000] Creating link /dev/char/235:59 => /dev/nvidia-caps/nvidia-cap59
INFO[0000] Creating link /dev/char/235:60 => /dev/nvidia-caps/nvidia-cap60
INFO[0000] Creating link /dev/char/235:61 => /dev/nvidia-caps/nvidia-cap61
INFO[0000] Creating link /dev/char/235:62 => /dev/nvidia-caps/nvidia-cap62
INFO[0000] Creating link /dev/char/235:63 => /dev/nvidia-caps/nvidia-cap63
INFO[0000] Creating link /dev/char/235:64 => /dev/nvidia-caps/nvidia-cap64
INFO[0000] Creating link /dev/char/235:65 => /dev/nvidia-caps/nvidia-cap65
INFO[0000] Creating link /dev/char/235:66 => /dev/nvidia-caps/nvidia-cap66
INFO[0000] Creating link /dev/char/235:67 => /dev/nvidia-caps/nvidia-cap67
INFO[0000] Creating link /dev/char/235:68 => /dev/nvidia-caps/nvidia-cap68
INFO[0000] Creating link /dev/char/235:69 => /dev/nvidia-caps/nvidia-cap69
INFO[0000] Creating link /dev/char/235:70 => /dev/nvidia-caps/nvidia-cap70
INFO[0000] Creating link /dev/char/235:71 => /dev/nvidia-caps/nvidia-cap71
INFO[0000] Creating link /dev/char/235:72 => /dev/nvidia-caps/nvidia-cap72
INFO[0000] Creating link /dev/char/235:73 => /dev/nvidia-caps/nvidia-cap73
INFO[0000] Creating link /dev/char/235:74 => /dev/nvidia-caps/nvidia-cap74
INFO[0000] Creating link /dev/char/235:75 => /dev/nvidia-caps/nvidia-cap75
INFO[0000] Creating link /dev/char/235:76 => /dev/nvidia-caps/nvidia-cap76
INFO[0000] Creating link /dev/char/235:77 => /dev/nvidia-caps/nvidia-cap77
INFO[0000] Creating link /dev/char/235:78 => /dev/nvidia-caps/nvidia-cap78
INFO[0000] Creating link /dev/char/235:79 => /dev/nvidia-caps/nvidia-cap79
INFO[0000] Creating link /dev/char/235:80 => /dev/nvidia-caps/nvidia-cap80
INFO[0000] Creating link /dev/char/235:81 => /dev/nvidia-caps/nvidia-cap81
INFO[0000] Creating link /dev/char/235:82 => /dev/nvidia-caps/nvidia-cap82
INFO[0000] Creating link /dev/char/235:83 => /dev/nvidia-caps/nvidia-cap83
INFO[0000] Creating link /dev/char/235:84 => /dev/nvidia-caps/nvidia-cap84
INFO[0000] Creating link /dev/char/235:85 => /dev/nvidia-caps/nvidia-cap85
INFO[0000] Creating link /dev/char/235:86 => /dev/nvidia-caps/nvidia-cap86
INFO[0000] Creating link /dev/char/235:87 => /dev/nvidia-caps/nvidia-cap87
INFO[0000] Creating link /dev/char/235:88 => /dev/nvidia-caps/nvidia-cap88
INFO[0000] Creating link /dev/char/235:89 => /dev/nvidia-caps/nvidia-cap89
INFO[0000] Creating link /dev/char/235:90 => /dev/nvidia-caps/nvidia-cap90
INFO[0000] Creating link /dev/char/235:91 => /dev/nvidia-caps/nvidia-cap91
INFO[0000] Creating link /dev/char/235:92 => /dev/nvidia-caps/nvidia-cap92
INFO[0000] Creating link /dev/char/235:93 => /dev/nvidia-caps/nvidia-cap93
INFO[0000] Creating link /dev/char/235:94 => /dev/nvidia-caps/nvidia-cap94
INFO[0000] Creating link /dev/char/235:95 => /dev/nvidia-caps/nvidia-cap95
INFO[0000] Creating link /dev/char/235:96 => /dev/nvidia-caps/nvidia-cap96
INFO[0000] Creating link /dev/char/235:97 => /dev/nvidia-caps/nvidia-cap97
INFO[0000] Creating link /dev/char/235:98 => /dev/nvidia-caps/nvidia-cap98
INFO[0000] Creating link /dev/char/235:99 => /dev/nvidia-caps/nvidia-cap99
INFO[0000] Creating link /dev/char/235:100 => /dev/nvidia-caps/nvidia-cap100
INFO[0000] Creating link /dev/char/235:101 => /dev/nvidia-caps/nvidia-cap101
INFO[0000] Creating link /dev/char/235:102 => /dev/nvidia-caps/nvidia-cap102
INFO[0000] Creating link /dev/char/235:103 => /dev/nvidia-caps/nvidia-cap103
INFO[0000] Creating link /dev/char/235:104 => /dev/nvidia-caps/nvidia-cap104
INFO[0000] Creating link /dev/char/235:105 => /dev/nvidia-caps/nvidia-cap105
INFO[0000] Creating link /dev/char/235:106 => /dev/nvidia-caps/nvidia-cap106
INFO[0000] Creating link /dev/char/235:107 => /dev/nvidia-caps/nvidia-cap107
INFO[0000] Creating link /dev/char/235:108 => /dev/nvidia-caps/nvidia-cap108
INFO[0000] Creating link /dev/char/235:109 => /dev/nvidia-caps/nvidia-cap109
INFO[0000] Creating link /dev/char/235:110 => /dev/nvidia-caps/nvidia-cap110
INFO[0000] Creating link /dev/char/235:111 => /dev/nvidia-caps/nvidia-cap111
INFO[0000] Creating link /dev/char/235:112 => /dev/nvidia-caps/nvidia-cap112
INFO[0000] Creating link /dev/char/235:113 => /dev/nvidia-caps/nvidia-cap113
INFO[0000] Creating link /dev/char/235:114 => /dev/nvidia-caps/nvidia-cap114
INFO[0000] Creating link /dev/char/235:115 => /dev/nvidia-caps/nvidia-cap115
INFO[0000] Creating link /dev/char/235:116 => /dev/nvidia-caps/nvidia-cap116
INFO[0000] Creating link /dev/char/235:117 => /dev/nvidia-caps/nvidia-cap117
INFO[0000] Creating link /dev/char/235:118 => /dev/nvidia-caps/nvidia-cap118
INFO[0000] Creating link /dev/char/235:119 => /dev/nvidia-caps/nvidia-cap119
INFO[0000] Creating link /dev/char/235:120 => /dev/nvidia-caps/nvidia-cap120
INFO[0000] Creating link /dev/char/235:121 => /dev/nvidia-caps/nvidia-cap121
INFO[0000] Creating link /dev/char/235:122 => /dev/nvidia-caps/nvidia-cap122
INFO[0000] Creating link /dev/char/235:123 => /dev/nvidia-caps/nvidia-cap123
INFO[0000] Creating link /dev/char/235:124 => /dev/nvidia-caps/nvidia-cap124
INFO[0000] Creating link /dev/char/235:125 => /dev/nvidia-caps/nvidia-cap125
INFO[0000] Creating link /dev/char/235:126 => /dev/nvidia-caps/nvidia-cap126
INFO[0000] Creating link /dev/char/235:127 => /dev/nvidia-caps/nvidia-cap127
INFO[0000] Creating link /dev/char/235:128 => /dev/nvidia-caps/nvidia-cap128
INFO[0000] Creating link /dev/char/235:129 => /dev/nvidia-caps/nvidia-cap129
INFO[0000] Creating link /dev/char/235:130 => /dev/nvidia-caps/nvidia-cap130
INFO[0000] Creating link /dev/char/235:131 => /dev/nvidia-caps/nvidia-cap131
INFO[0000] Creating link /dev/char/235:132 => /dev/nvidia-caps/nvidia-cap132
INFO[0000] Creating link /dev/char/235:133 => /dev/nvidia-caps/nvidia-cap133
INFO[0000] Creating link /dev/char/235:134 => /dev/nvidia-caps/nvidia-cap134
INFO[0000] Creating link /dev/char/235:135 => /dev/nvidia-caps/nvidia-cap135
INFO[0000] Creating link /dev/char/235:136 => /dev/nvidia-caps/nvidia-cap136
INFO[0000] Creating link /dev/char/235:137 => /dev/nvidia-caps/nvidia-cap137
```

**Comment by elezar** [comment]
@mfuntowicz could we start by confirming that `nvidia-smi` works in a basic container:
```
docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all nvidia-smi -L
```
This should provide the same information as on the host.

Note that one of the sideeffects of the issue is that device nodes MUST be specified on the docker command line.

Since you're using Docker 25 you could consider using CDI mode instead (see https://docs.docker.com/reference/cli/dockerd/#enable-cdi-devices).

Do the following:
1. Enable CDI in docker:
```
sudo nvidia-ctk runtime configure --runtime=docker --cdi-enabled
```
2. Restart the Docker daemon:
```
sudo systemctl restart docker
```

Now it is required to generate a CDI specifiation using the `nvidia-ctk cdi generate` command. This should detect the devices available on your system and generate CDI specifications for them.

Run:
```
sudo nvidia-ctk cdi generate --output=/var/run/cdi/nvidia.yaml
```
to generate a CDI specification and store it in `/var/run/cdi/nvidia.yaml`

The list of available CDI devices can be obtained by runnning:
```
nvidia-cdi cdi list
```
For example:
```
$ nvidia-ctk cdi list
INFO[0000] Found 9 CDI devices
nvidia.com/gpu=0
nvidia.com/gpu=1
nvidia.com/gpu=2
nvidia.com/gpu=3
nvidia.com/gpu=4
nvidia.com/gpu=5
nvidia.com/gpu=6
nvidia.com/gpu=7
nvidia.com/gpu=all
```

**Note:** The CDI specification will have to be regenerated at boot or when the driver installation changes. We are still working on making this process more streamlined.

To run your container then use:
```
docker run -it --rm --device=nvidia.com/gpu=all huggingface/optimum-nvidia:0.1.0b3 bash
```
Where it is assume that you want access to all NVIDIA devices hence the `nvidia.com/gpu=all` CDI device name.

**Comment by mfuntowicz** [comment]
Ok, I used `ubuntu:22.04` as docker image (which was not specified in your comment): 

```bash
➜  open-gpu-kernel-modules git:(550.54.14) docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all ubuntu:22.04 nvidia-smi -L
Failed to initialize NVML: Unknown Error
```

**Comment by lukaemon** [comment]
I just install fresh ubuntu, docker and container toolkit then run the simple `docker run --gpus=all --runtime=nvidia --rm nvcr.io/nvidia/cuda:11.6.2-base-ubuntu20.04 nvidia-smi`

Got the same error message. Looking forward to finding the root cause.

**Comment by jacksonsc007** [comment]
hi everyone, @lukaemon  @mfuntowicz  @elezar  
I encountering this problem today and solved it by degrading the version of nvidia-container-toolkit
```
# first remove the old ones
sudo apt remove --purge nvidia-container-toolkit
sudo apt update
sudo apt autoremove

# check version availability
apt list -a "*nvidia-container-toolkit*"
# install 1.14.0-1
apt install nvidia-container-toolkit=1.14.0-1 nvidia-container-toolkit-base=1.14.0-1
```
Attaching my driver version:
```
(base) ink@workstation:~$ nvidia-smi
Sun Mar  3 11:51:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
|  0%   22C    P8              21W / 450W |      3MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

```

**Comment by elezar** [comment]
> I encountering this problem today and solved it by degrading the version of nvidia-container-toolkit

Which version were you using before this?

**Comment by mfuntowicz** [comment]
Hi @elezar I confirm it works with `1.14.0-1` on my machine but fails with `1.14.1` see below:

```bash
➜  ~ sudo dnf install nvidia-container-toolkit-1.14.0-1.x86_64
Last metadata expiration check: 1:26:51 ago on Mon 04 Mar 2024 10:05:25 AM CET.
Dependencies resolved.
========================================================================================================================================================================================================================================================================================
 Package                                                                         Architecture                                             Version                                                      Repository                                                                  Size
========================================================================================================================================================================================================================================================================================
Downgrading:
 nvidia-container-toolkit                                                        x86_64                                                   1.14.0-1                                                     nvidia-container-toolkit                                                   975 k
 nvidia-container-toolkit-base                                                   x86_64                                                   1.14.0-1                                                     nvidia-container-toolkit                                                   3.3 M
Downgraded:
  nvidia-container-toolkit-1.14.0-1.x86_64                                                                                                 nvidia-container-toolkit-base-1.14.0-1.x86_64

Complete!
➜  ~ docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all ubuntu:22.04 nvidia-smi -l
Mon Mar  4 10:33:00 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:65:00.0 Off |                  Off |
| 30%   31C    P0             64W /  450W |       0MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

1.14.1.1:
```bash
➜  ~ sudo dnf install nvidia-container-toolkit-1.14.1-1.x86_64
Last metadata expiration check: 1:27:54 ago on Mon 04 Mar 2024 10:05:25 AM CET.
Dependencies resolved.
========================================================================================================================================================================================================================================================================================
 Package                                                                         Architecture                                             Version                                                      Repository                                                                  Size
========================================================================================================================================================================================================================================================================================
Upgrading:
 nvidia-container-toolkit                                                        x86_64                                                   1.14.1-1                                                     nvidia-container-toolkit                                                   975 k
 nvidia-container-toolkit-base                                                   x86_64                                                   1.14.1-1                                                     nvidia-container-toolkit                                                   3.3 M
Upgraded:
  nvidia-container-toolkit-1.14.1-1.x86_64                                                                                                 nvidia-container-toolkit-base-1.14.1-1.x86_64

Complete!
➜  ~ docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all ubuntu:22.04 nvidia-smi -l
Failed to initialize NVML: Unknown Error
```

Back to 1.14.0.1 again (as a sanity check)
```bash
➜  ~ sudo dnf install nvidia-container-toolkit-1.14.0-1.x86_64
Last metadata expiration check: 1:28:15 ago on Mon 04 Mar 2024 10:05:25 AM CET.
Dependencies resolved.
========================================================================================================================================================================================================================================================================================
 Package                                                                         Architecture                                             Version                                                      Repository                                                                  Size
========================================================================================================================================================================================================================================================================================
Downgrading:
 nvidia-container-toolkit                                                        x86_64                                                   1.14.0-1                                                     nvidia-container-toolkit                                                   975 k
 nvidia-container-toolkit-base                                                   x86_64                                                   1.14.0-1                                                     nvidia-container-toolkit                                                   3.3 M

Transaction Summary
========================================================================================================================================================================================================================================================================================
Downgrade  2 Packages
Downgraded:
  nvidia-container-toolkit-1.14.0-1.x86_64                                                                                                 nvidia-container-toolkit-base-1.14.0-1.x86_64

Complete!
➜  ~ docker run --rm -ti --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all ubuntu:22.04 nvidia-smi -l
Mon Mar  4 10:33:54 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090        Off |   00000000:65:00.0 Off |                  Off |
| 30%   30C    P0             65W /  450W |       0MiB /  24564MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by elezar** [comment]
@mfuntowicz is the error still present in `v1.14.6`?

Also, could you provide the contents of `/etc/nvidia-container-runtime/config.toml`? This

**Comment by mfuntowicz** [comment]
Yes NVML error still present with `v1.14.6` 

Here is the content of `/etc/nvidia-container-runtime/config.toml`

```toml
#accept-nvidia-visible-devices-as-volume-mounts = false
#accept-nvidia-visible-devices-envvar-when-unprivileged = true
disable-require = false
supported-driver-capabilities = "compat32,compute,display,graphics,ngx,utility,video"
#swarm-resource = "DOCKER_RESOURCE_GPU"

[nvidia-container-cli]
#debug = "/var/log/nvidia-container-toolkit.log"
environment = []
#ldcache = "/etc/ld.so.cache"
ldconfig = "@/sbin/ldconfig"
load-kmods = true
no-cgroups = true
#path = "/usr/bin/nvidia-container-cli"
#root = "/run/nvidia/driver"
#user = "root:video"

[nvidia-container-runtime]
#debug = "/var/log/nvidia-container-runtime.log"
log-level = "info"
mode = "auto"
runtimes = ["docker-runc", "runc", "crun"]

[nvidia-container-runtime.modes]

[nvidia-container-runtime.modes.cdi]
annotation-prefixes = ["cdi.k8s.io/"]
default-kind = "nvidia.com/gpu"
spec-dirs = ["/etc/cdi", "/var/run/cdi"]

[nvidia-container-runtime.modes.csv]
mount-spec-path = "/etc/nvidia-container-runtime/host-files-for-container.d"

[nvidia-container-runtime-hook]
path = "nvidia-container-runtime-hook"
skip-mode-detection = false

[nvidia-ctk]
path = "nvidia-ctk"
```

**Comment by Hasipasi** [comment]
@mfuntowicz try setting no-cgroups to false, fixed my issue.

**Comment by elezar** [comment]
@mfuntowicz if this works on your end, this would explain the behaviour. the v1.14.0 release had a bug where settings in the `config.toml` were being ignored. This would mean that `no-cgroups = false` was being applied.

In general `no-cgroups = false` is only needed for rootless containers. Do you recall if you applied this setting yourself?

**Comment by klueska** [comment]
@elezar I believe you mean that `no-cgroups = **true**` is only needed for rootless containers.

**Comment by elezar** [comment]
> @elezar I believe you mean that `no-cgroups = true` is only needed for rootless containers.

Yes. I have corrected my message.

**Comment by lukaemon** [comment]
> @mfuntowicz try setting no-cgroups to false in `/etc/nvidia-container-runtime/config.toml` , fixed my issue.

Works for me. Thx.

**Comment by gonidelis** [comment]
> hi everyone, @lukaemon @mfuntowicz @elezar I encountering this problem today and solved it by degrading the version of nvidia-container-toolkit
> 
> ```
> # first remove the old ones
> sudo apt remove --purge nvidia-container-toolkit
> sudo apt update
> sudo apt autoremove
> 
> # check version availability
> apt list -a "*nvidia-container-toolkit*"
> # install 1.14.0-1
> apt install nvidia-container-toolkit=1.14.0-1 nvidia-container-toolkit-base=1.14.0-1
> ```
> 
> Attaching my driver version:
> 
> ```
> (base) ink@workstation:~$ nvidia-smi
> Sun Mar  3 11:51:13 2024       
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
> |  0%   22C    P8              21W / 450W |      3MiB / 24564MiB |      0%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
>                                                                                          
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |  No running processes found                                                           |
> +---------------------------------------------------------------------------------------+
> ```

This worked for me! Thanx!

**Comment by elezar** [comment]
@gonidelis could you also confirm your `/etc/nvidia-container-runtime/config.toml` and the version you were using before you downgraded?

**Comment by mfuntowicz** [comment]
Thanks everyone - @elezar @Hasipasi I'm testing this after working our, keeping my setup working now
Keeping you posted later today

**Comment by charithmu** [comment]
Hi all,
I can confirm that changing `no-cgroups = false` in `/etc/nvidia-container-runtime/config.toml` works for me as well.

Setup:
Ubuntu 20.04.6 LTS
Docker version 25.0.4, build 1a576c5
NVIDIA Container Runtime Hook version 1.14.6
commit: 5605d191332dcfeea802c4497360d60a65c7887e
Driver Version: 550.54.14      CUDA Version: 12.4

**Comment by mfuntowicz** [comment]
Worked for me as well! 

Thanks a ton @elezar @Hasipasi for the support here 🙏🤗.

Closing this issue as it's now fixed 😊.

**Comment by gknagoing** [comment]
> > @mfuntowicz try setting no-cgroups to false in `/etc/nvidia-container-runtime/config.toml` , fixed my issue.
> 
> Works for me. Thx.

This also solved my problem

**Comment by anubhav-agrawal-mu-sigma** [comment]
How can we enable both rootless and root nvidia container toolkit. If I enable no-cgroups = true, I cannot use GPU in root docker, if I do no-cgroups = false, cannot access GPU in rootless/user docker.

**Comment by jin-sss** [comment]
> hi everyone, [@lukaemon](https://github.com/lukaemon) [@mfuntowicz](https://github.com/mfuntowicz) [@elezar](https://github.com/elezar) I encountering this problem today and solved it by degrading the version of nvidia-container-toolkit
> 
> ```
> # first remove the old ones
> sudo apt remove --purge nvidia-container-toolkit
> sudo apt update
> sudo apt autoremove
> 
> # check version availability
> apt list -a "*nvidia-container-toolkit*"
> # install 1.14.0-1
> apt install nvidia-container-toolkit=1.14.0-1 nvidia-container-toolkit-base=1.14.0-1
> ```
> 
> Attaching my driver version:
> 
> ```
> (base) ink@workstation:~$ nvidia-smi
> Sun Mar  3 11:51:13 2024       
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
> |  0%   22C    P8              21W / 450W |      3MiB / 24564MiB |      0%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
>                                                                                          
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |  No running processes found                                                           |
> +---------------------------------------------------------------------------------------+
> ```


works for me !!!!!
Remember to restart the container after executing these commands.  :>
